mqtt:
  # The hostname or IP address of the MQTT broker to connect to (Default: localhost). Required.
  hostname: 127.0.0.1
  # The TCP port the MQTT broker is listening on (Default: 1883). Required.
  port: 1883
  # The ID of this python program to use when connecting to the MQTT broker (Default: rpi-mqtt). Required.
  client_id: rpi-mqtt

script:
  # The interval to update sensor data to MQTT broker. In seconds. (Default: every 60 sec). Required.
  update_interval: 60
  # The log level for the python script
  log_level: ERROR

# Enable (true) or disable (false) sensors you want to be published to MQTT broker
sensors:
  boot_loader: True
  cpu: True
  disk: True
  fan: True
  memory: True
  network: True
  os: True
  temperature: True
  throttle: True
